language: python
python:
- '3.8'
before_install:
- openssl aes-256-cbc -K $encrypted_9a283e415df1_key -iv $encrypted_9a283e415df1_iv
  -in ddyzd-firebase-adminsdk.json.enc -out ddyzd-firebase-adminsdk.json -d
install:
- pip install -r requirements.txt
script:
- mkdir logs
- python -m pytest
